### ISSUE TITLE
Anthologia Lyrica and Anthologia Lyrica Graeca-data mixup

### ISSUE THREAD

**Issue by AlisonBabeu** [agile-humanities/perseus-catalog-makeover#12]
Hi @cwulfman, so per our conversation Saturday I am opening an issue regarding this composite work that seemed to have a rather large error in its data conversion.

The edition in question is Anthologia Lyrica by Eduard Hiller that starts at line 2578. The inverted MODS record contains only one work when there should be dozens.  The error seems to start at line 2862 for work urn:cts:greekLit:tlg0256.tlg001.opp-grc3. Having looked at this record in catalog_data it looks like I erroneously put the editor for this work/expression as Hiller, when it should have been Ernst Diehl. Perhaps that triggered adding the next group of expressions to Anthologia Lyrica Graeca, Volume 3, rather than the original Anthologia Lyrica. It appears then that all of the work/expressions between lines 2870 and 3578 should be added to the original Anthologia Lyrica at line 2578. I am willing to try doing this by hand but was wondering if you could perhaps try running an inversion again on the selected Anthologia Lyrica files and see if something else is going on.

**Comment by cwulfman** [comment]
I spent days on the Lyra Graeca back in April, constructing an outline by hand from the table of contents in the Loeb edition. It isn't surprising that some glitches crept in. Let me reconstruct what I did and get back to you.

**Comment by AlisonBabeu** [comment]
Hi @cwulfman, the Lyra Graeca is a separate edition entirely, I haven't looked at the one yet. Lyra Graeca is a several volume edition by Loeb, the one to which I refer it a Greek only Teubner edition.

**Comment by cwulfman** [comment]
Good to know!

**Comment by cwulfman** [comment]
I need to step back and get my head straight about these editions.

What is the relationship of these editions to <https://en.wikipedia.org/wiki/Greek_Anthology>? 

I produced a very detailed hand-crafted version from the Perseus TEI transcription, so the auto-generated version should be trashed (the hand-crafted version is attached here; the work/expression/structure structure needs to be brought up to our current practice, but that won't be impossible, though it will take some mapping from all those extant ctsurns for all the fragments). Can any of that structure be borrowed?

[tlg7000.tlg001.mods.xml.zip](https://github.com/agile-humanities/perseus-catalog-makeover/files/2069211/tlg7000.tlg001.mods.xml.zip)

**Comment by AlisonBabeu** [comment]
There is only a tangential relationship. Many of the author-works found in the Greek Anthology (GA) are also found in these other series but they also contain other authors who wrote Greek lyric poetry and not just epigrams. And in terms of the MODS file you attached, should that be used to replace the current Greek Anthology in inverted.mods.xml?

**Comment by cwulfman** [comment]
Eventually -- when I created that record (lovingly!) I didn't know how to map the sections to specific editions/translations of each. I'll take that on.

**Comment by AlisonBabeu** [comment]
Well there is only one edition of the Greek Anthology in the Perseus
Catalog at least so there should only be one edition, where each epigram
has a Greek original and an English translation.

**Comment by cwulfman** [comment]
What are the remaining outstanding issues for Anthologia Lyrica by Eduard Hiller?

**Comment by AlisonBabeu** [comment]
What happened here was that most of the works from this edition ended up in another Anthologia Lyrica MODS record. We never figured out why but I think in all honesty this one will be a hand editing fix and double check.

**Comment by cwulfman** [comment]
@AlisonBabeu did these get untangled? Can I close this ticket?

**Comment by AlisonBabeu** [comment]
They aren't untangle but you can close it because I've noted it in the file and was planning to deal with it later.
