### ISSUE TITLE
identifiers for manifestations

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/perseus-catalog-makeover#13]
I need identifiers for the manifestations (MODS records).
 
CTS urns refer to expressions, which may be carried by several manifestations. I need to be able to retrieve a specific MODS record, so it needs some kind of identifier. Thoughts about how to do that? There are several options:

1. `<mods ID="someID">`
2. ` <recordInfo><recordIdentifier>someID</recordIdentifier></recordInfo>`

We can't rely on external IDs, because not all of our manifestations will have them (e.g., the Perseus transcriptions).

I prefer the `<recordIdentifier>` method. Thoughts?

**Comment by AlisonBabeu** [comment]
So is the number one in the list up there left deliberately blank because you couldn't think of a method 1. Also you apparently have decided to keep the method you prefer a mystery! :)

I agree that we can't use external IDs and I certainly don't want to try and create any semantic ones. What exactly is someID again?

**Comment by cwulfman** [comment]
Sorry! -- stealth formatting (I left out the `` around the xml).

Some ID is -- *sigh* something we'd generate. It can and should be entirely opaque.

**Comment by AlisonBabeu** [comment]
I prefer the second method as well, I also greatly prefer something we generate that is opaque. And I hate it too when I forget the `` around the XML. Markdown late at night can be entertaining reading the next day. :)

**Comment by cwulfman** [comment]
Moved to https://github.com/PerseusDL/catalog_data/issues/162
