### ISSUE TITLE
Grammatici Graeci record

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/perseus-catalog-makeover#14]
I'm getting into some of the sketchier records in catalog_pendng: they are associated with no ctsurn, but may have a tlg id. In this case, there are two fragmentary mods, one each for two volumes of a series. 

Doing my own research on Hathi, and then finding [a LibraryThing entry](https://www.librarything.com/series/Grammatici+Graeci), I've pieced together a record that encompasses the two volumes.  It is attached; please take a look and let me know what you think -- I'm not sure about it.

I'm just figuring out what you already no doubt knew, namely that there will be a number of records in catalog pending that will need work CTS urns minted for them.

[grammatici_graeci.mods.xml.zip](https://github.com/agile-humanities/perseus-catalog-makeover/files/2088257/grammatici_graeci.mods.xml.zip)

**Comment by AlisonBabeu** [comment]
Yes, in fact most of the works in catalog_pending will need to have CTS URNs minted for them. The reason that some of these files have URNs is that they were already within the First1K collection so they had URNs already.
