### ISSUE TITLE
Chronographia record in catalog_pending

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/perseus-catalog-makeover#16]
This is part of Muller's Fragmenta historicorum graecorum is in catalog pending; there are twelve others. We already have a record for Muller, though there is no constituent for this item. What we really should have is a full structure of Muller; right now it is at the Volume level, with sub-parts associated with already-extant expressions.

[chronographia.mods.xml.zip](https://github.com/agile-humanities/perseus-catalog-makeover/files/2100206/chronographia.mods.xml.zip)

**Comment by AlisonBabeu** [comment]
Hi @cwulfman.  I'm a little confused by this MODS record. For instance, why is FHG V a constituent rather than a host for this work. Is that just an error?  And from the empty identifier in the work constituent section, I assume that is because we have not yet coined CTS-URNs for all of the works in catalog_pending?  I think I can help develop a pattern to generate this automatically if needed, or of course create a number manually if necessary.

And by twelve others do you mean there are twelve other author/work records for Mueller in catalog_pending? because when I search on `<title>Fragmenta historicorum graecorum</title>` in catalog_pending I find 93 authors/works that are missing from the five volume series, the rest of Volume 4 and 5, and a few missing ones form Volume 3.

**Comment by cwulfman** [comment]
First -- I erred on the number of records (I did a string search for Müller and didn't realize there were two of them!).

So: those author/works in catalog_pending need to be merged into the record for FHG in inverted.mods.xml, right? I can do that.

**Comment by AlisonBabeu** [comment]
Yes, that would be epic (as my six year old likes to say these days)! And thank you!

**Comment by cwulfman** [comment]
Ok -- I gave up trying to sort the FHG into books, according to Monica's toc. Attached, then, is the FHG record with, I think, everything from mods_pending. Could you give it a look-over and see if you see anything I've missed/messed up?

[FHG.mods.xml.zip](https://github.com/agile-humanities/perseus-catalog-makeover/files/2107564/FHG.mods.xml.zip)

**Comment by AlisonBabeu** [comment]
HI @cwulfman I'll take a look at it, no problem.

**Comment by AlisonBabeu** [comment]
Hi @cwulfman , one question. There are a number of records from catalog_pending in this file that don't follow the format of the others, should I alter them to fit this format, or just move them to their right section and not bother with that?

**Comment by cwulfman** [comment]
Hi @AlisonBabeu could you point me to one of the records that doesn't match the others?

**Comment by AlisonBabeu** [comment]
Sure. For example, the record for Claudius Eusthenius in the FHG file ended up looking like this:
```xml
<relatedItem type="constituent" otherType="section" displayLabel="Claudius Eusthenius">
          <titleInfo>
            <title>Fragmenta</title>
          </titleInfo>
          <name authority="viaf" type="personal" xlink:href="http://viaf.org/viaf/42230153">
            <namePart>Claudius</namePart>
            <namePart type="termsOfAddress">Eusthenius</namePart>
            <namePart type="date">4. Jh. n. Chr.</namePart>
            <role>
              <roleTerm authority="marcrelator" type="text">creator</roleTerm>
            </role>
          </name>
          <part type="FHG">
            <detail>
              <title>FHG 3: 728</title>
            </detail>
          </part>
          <part type="FGrH">
            <detail>
              <title>FGrH #218</title>
            </detail>
          </part>
          <part>
            <extent unit="pages">
              <start>729</start>
              <end>729</end>
            </extent>
          </part>
          <relatedItem type="constituent" otherType="work" displayLabel="Fragmenta">
            <identifier type="tlg">1971.001</identifier>
            <relatedItem type="constituent" otherType="expression">
              <location>
                <url displayLabel="GoogleBooks"
                  >http://books.google.com/books?id=oqcKAAAAYAAJ&amp;pg=PA728</url>
              </location>
              <location>
                <url displayLabel="Open Content Alliance"
                  >http://www.archive.org/stream/fragmentahistori03mueluoft#page/728/mode/2up</url>
              </location>
            </relatedItem>
          </relatedItem>
        </relatedItem>
```
rather than the typical format say for Dexippus Herennius 
```xml
        <relatedItem type="constituent" otherType="section" displayLabel="Dexippus, Publius Herennius">
          <relatedItem type="constituent" otherType="work" displayLabel="Fragmenta">
            <identifier type="ctsurn">urn:cts:greekLit:tlg2141.tlg003</identifier>
            <titleInfo>
              <title>Fragmenta</title>
            </titleInfo>
            <name>
              <namePart>Dexippus, Publius Herennius</namePart>
              <nameIdentifier type="ctsurn">urn:cts:greekLit:tlg2141</nameIdentifier>
              <role>
                <roleTerm type="text" authority="marcrelator">creator</roleTerm>
              </role>
            </name>
            <relatedItem type="constituent" otherType="expression">
              <identifier type="ctsurn">urn:cts:greekLit:tlg2141.tlg003.opp-grc2</identifier>
            </relatedItem>
            <relatedItem type="constituent" otherType="expression">
              <identifier type="ctsurn">urn:cts:greekLit:tlg2141.tlg003.opp-lat1</identifier>
            </relatedItem>
          </relatedItem>
        </relatedItem>   
        <relatedItem>
```
I assumed that some of the info currently in the records from catalog pending would end up in the manifestation level records, rather than this top level record. I was hoping to finally return to this file today (I've made it up to volume 4!). I've noted a few questions/issues but I wanted to finish the file before commenting more.

**Comment by cwulfman** [comment]
Thanks. (I've been away from this for a while and lost context.) Yes -- please do alter them to fit the typical format as you move them.

**Comment by AlisonBabeu** [comment]
Will do. Do you still want to meet on Friday or push it off til next week? I've been buried by NEH Institute business but will have more time the end of this week to push more on the data!

**Comment by AlisonBabeu** [comment]
So as promised @cwulfman , here is the FHG file! 
[FHG.mods.xml.zip](https://github.com/agile-humanities/perseus-catalog-makeover/files/2220906/FHG.mods.xml.zip)
