### ISSUE TITLE
finish converting the MODS from catalog_pending

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/perseus-catalog-makeover#17]
The singletons have been competed; there are 75-100 inverted records to hand-clean.

**Comment by AlisonBabeu** [comment]
Hi @cwulfman so should I be looking at these yet, or not yet? Thanks!

**Comment by cwulfman** [comment]
Yes, but only <https://github.com/agile-humanities/perseus-catalog-makeover/blob/develop/mods/singletons.mods.xml> so far.

**Comment by AlisonBabeu** [comment]
Question @cwulfman that link above links to the MODS singletons that I have been working with over the last few month, I was thinking about looking at the MODS records from catalog_pending (are those here: https://github.com/agile-humanities/perseus-catalog-makeover/blob/develop/mods/from_catalog_pending/pending-singletons.mods.xml) and should they not be looked at yet?

**Comment by cwulfman** [comment]
Sorry - you're right about the link. It is pending-singletons.mods.xml that you should look at.

**Comment by cwulfman** [comment]
@AlisonBabeu https://github.com/agile-humanities/perseus-catalog-makeover/blob/develop/mods/from_catalog_pending/pending-inverted.mods.xml is checked in and can be reviewed.

**Comment by AlisonBabeu** [comment]
Hi @cwulfman, just wanted to make sure this file is the most recent as it says in the GitHub repo that pending-inverted.mods.xml was last updated four days ago, should that be correct? Thanks!

**Comment by cwulfman** [comment]
That's right!
