### ISSUE TITLE
Missing piece of data from MODS records in inverted.mods.xml

### ISSUE THREAD

**Issue by AlisonBabeu** [agile-humanities/perseus-catalog-makeover#18]
Hi @cwulfman. So as I have returned to reviewing the inverted MODS records I was noting there is almost a complete lack of series information. 

I reviewed a number of the MODS records both in this file and within their original catalog_data locations and for some reason, the element did not get carried forward.
```xml 
<relatedItem type="series">
	    <titleInfo type="abbreviated">
            <title>Teubner</title>
</titleInfo>
```
I first noticed this because I had started to add series info into a few records that never had them, and wondered where all the Teubner series statements had gone.

**Comment by AlisonBabeu** [comment]
As a follow up to this question, I've long wanted to add series information to those records that were missing it, so could we say set up a script that finds certain patterns and then adds a series element to the relevant MODS records?

**Comment by cwulfman** [comment]
I'll look at this. Meanwhile, could you either (a) email me your latest copies of the mods records (singletons.mods.xml and inverted.mods.xml) or (b) check them into the develop branch?

**Comment by cwulfman** [comment]
Issue moved to https://github.com/PerseusDL/catalog_data/issues/159
