### ISSUE TITLE
Generate RDF for expressions and manifestations, linked with HuCit, from the MODS data.

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/perseus-catalog-makeover#19]

**Comment by cwulfman** [comment]
I've now generated the RDF from the AAE spreadsheets, as they stand today. They are in a directory called rdf/, and will be one of the final deliverables.

**Comment by cwulfman** [comment]
This entire github repo should go away once we're done. The RDF should be packaged up with a README and delivered; Alison or someone in Perseus should figure out where they want to put it.

**Comment by AlisonBabeu** [comment]
Hi @cwulfman , so do you mean that the Agile repository needs to go away eventually? I would be happy to have everything live in catalog_data ultimately. We can talk more on this at the end of the week. And btw, as I update the info in the spreadsheets, will I be able to run a script to generate updated RDF? 
Thanks (and I'm backkkkk.....)

**Comment by cwulfman** [comment]
Perseus should "own" Perseus's assets in a space it controls. (I say that somewhat ironically, since no one at Perseus currently seems to have administrative rights to Perseus's GitHub organization...).

Let's do plan to talk at the end of the week, when I hope to have the final deliverables ready to hand over so I can get paid. We can talk about what happens next after that.

(And welcome back!  Hope you had a great vacation!)

**Comment by cwulfman** [comment]
There are some things that may make it hard for you to generate updated RDF from the spreadsheets, because I had to go in after I generated the data and hand-tweak things. E.g., where you record two authors in one cell ("A and B" in the name cell, "???    ???) in the viafid cell.

Or wrong data in a cell, as in "yes-IA has scanned" in a VIAFID cell

**Comment by AlisonBabeu** [comment]
Oops! I will continue cleaning the data for some further RDF conversion in the sky! :)

**Comment by cwulfman** [comment]
I hope it isn't so abstract: I've spent a good deal of the summer working on it....   :)

**Comment by AlisonBabeu** [comment]
I'm sure it won't be and too abstract, I only recently discovered those two names in a name cell, sigh, it was a way of trying to represent attributed authors, etc. The original spreadsheet for this work is over 10 years old so its more than legacy at this point, its ancient! :P

**Comment by cwulfman** [comment]
Closing this now; linking with HuCit data will be another project.
