### ISSUE TITLE
Mueller.mods.xml-Possible reason for Volume identification issue

### ISSUE THREAD

**Issue by AlisonBabeu** [agile-humanities/perseus-catalog-makeover#2]
Hi @cwulfman so I've taken a quick pass over the FHG mega volume. 

1) I'm assuming that volume 0 has been used to gather all those authors where the correct volume could not be identified, yes?

2) I started digging in and did a check of volume one, where all of the authors from the volume were pulled correctly into this new manifestation level file. As a sanity check I used my original MODS record for the entire FHG I volume. I then moved on to  volume 2 and found that it lists only two authors, the first of which is Craterus of Macedon. So I went to take a look at the [original MODS record](https://github.com/PerseusDL/catalog_data/blob/master/mods/greekLit/tlg1288/tlg003/opp-grc1/tlg1288.tlg003.opp-grc1.mods1.xml)  within catalog data to see what might make this file different from all the other authors.

It looks like I manually changed this file in 2015, and what I did was removed a double `<relatedItem type="host"` element error that I believe was causing display issues in Blacklight (https://github.com/PerseusDL/catalog_data/commit/7c12eb6b2457db571a77305f66df19c7256581e5). I removed the first "host", which although technically correct in terms of _Books_, was not the host **volume**.

```xml
  <mods:relatedItem xmlns="http://www.loc.gov/mods/v3"
-                     type="host"
-                     displayLabel="Liber Quartus">
-                    <mods:titleInfo>
-                        <mods:title>Liber Quartus</mods:title>
-                        <mods:subTitle>Reliqui Scriptores Qui Florerunt Inde Ab Alexandri Temporibus Usque Ad Mortem
-                Ptolemaei Philadelphi (336-247 a.C.)</mods:subTitle>
-                    </mods:titleInfo>
                     <mods:relatedItem type="host">
                     <mods:relatedItem type="host">
                         <mods:titleInfo>
                         <mods:titleInfo>
                             <mods:title>Fragmenta historicorum graecorum</mods:title>
```
When I had cataloged all of these volumes back in the day, I had created `<relatedItem type="constituent"` for all of the "Books" within them and then had more `<relatedItem type="constituents"` for all of the authors within those books. I believe when the MODS records for catalog_data were originally generated this fact caused a number of issues.  I have a feeling that any MODS record within catalog_data that had a double host ended up in the Volume 0 section.

For example, I looked up the MODS record for the very first author found in Volume 0, Abydenus Historicus [(urn:cts:greekLit:tlg0116.tlg002.opp-grc1)](https://github.com/PerseusDL/catalog_data/blob/master/mods/greekLit/tlg0116/tlg002/opp-grc1/tlg0116.tlg002.opp-grc1.mods1.xml) and sure enough it has the dreaded double host MODS encoding (henceforth known as DDHME)
```xml
 <mods:relatedItem xmlns="http://www.loc.gov/mods/v3" type="host" displayLabel="X">
                    <mods:titleInfo>
                        <mods:title>Liber Decimus</mods:title>
                        <mods:subTitle>Scriptores Aetatis Incertae Ex Ordine Literarum</mods:subTitle>
                    </mods:titleInfo>
                    <mods:relatedItem type="host">
                        <mods:titleInfo>
                            <mods:title>Fragmenta historicorum graecorum</mods:title>
                            <mods:partNumber>Vol IV</mods:partNumber>
</mods:titleInfo>
```
So does this make any sense at all, and if it does, how do we fix it is the next question? (I"ll think on that after more coffee).

**Comment by cwulfman** [comment]
I've been coming at those doubly-embedded hosts from a different direction -- interesting.

I have a skeletal outline of the volumes (attached here); maybe we could figure out a way to resolve these beasties.

[historiangroups.xml.zip](https://github.com/agile-humanities/perseus-catalog-makeover/files/1880481/historiangroups.xml.zip)

**Comment by AlisonBabeu** [comment]
Sorry @cwulfman  for some reason I just saw that there was  a zip file here with a new XML record. The email just showed up with the first line. I'll take a look at this and think on it a bit.

**Comment by cwulfman** [comment]
[muller.mods.xml.zip](https://github.com/agile-humanities/perseus-catalog-makeover/files/2011020/muller.mods.xml.zip)
@AlisonBabeu I think I've resolved the "volume 0"  problem. Attached is a new MODS for Muller; let me know what you think.

**Comment by AlisonBabeu** [comment]
Hi @cwulfman so this looks really great. I actually spent the morning going through volume 1-3 and it doesn't look like anything is missing at all. 

I also like the format that breaks down the work information/author information/ vs. expression. Its very clear.
Just a few thoughts/question:

1) I noticed that each constituent record includes a textgroup name identifier
`     <nameIdentifier type="ctsurn">urn:cts:greekLit:tlg0392</nameIdentifier>`
for author names. I also wondered if we might want to add the citeurn for author names in the authority records to this space as well, in order to link these constituents to the authority record. In this case for Acusilaus of Argos it would be:
`    <nameIdentifier type="citeurn">urn:cite:perseus:author.14.1</nameIdentifier>`

2) Have we decided yet what the expression level records will look like? I'm just wondering what all the currently left behind MODS data (TOC data, alternate and abbreviated titles, page level data and online links, etc.) will look like?

**Comment by cwulfman** [comment]
I'm thrashing a bit about the relationship between the RDF and the MADS/MODS. I've been thinking relationship info like author/translator maybe stays in the RDF, but I'm not sure any more.  Keeping it in MADS/MODS makes it easier to build an XML-based catalog browser using eXist, because all the data is available via XQuery. But I also want to connect up with Matteo's FRBRoo stuff. I'm beginning to wonder if there shouldn't be a MADS/MODS conversion phase and then a FRBRoo LOD phase, just to stay sane and focused.

As for what expression-level records should look like: I've been taking a minimalistic approach so far; figuring out what of that metadata to bring over, where it goes, etc., seems like it could be quite a challenge, and in some cases redundant. Shall we start working on an informal profile in the Wiki?

**Comment by AlisonBabeu** [comment]
I think an informal profile in the wiki would be a good place to start! And I think a MADS/MODS conversion phase before a FRBRoo phase would be a good way to see how all this data conversion is going...
