### ISSUE TITLE
remove cts urns from MODS records

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/perseus-catalog-makeover#24]
We've changed our conception of what the MODS records are for: they are for Manifestation Product Types, not Expressions. (They carry expressions). So the MODS record is not the expression, and shouldn't have <identifier type='ctsurn'>.

Similarly, they should not have tlg ids: they are not the works.

**Comment by AlisonBabeu** [comment]
Well the CTS-URNs currently in the MODS records are contained within structural expression constituents so semantically that is consistent.  If we weren't thinking of having lists of the URNs and work/expressions within a MODS record so we could quickly see what the manifestation contains, where were you thinking they would live.

**Comment by cwulfman** [comment]
That's what the identifiers in each of the <relatedItem> elements are for, right?

**Comment by AlisonBabeu** [comment]
I'm not entirely sure I"m following but we can discuss tomorrow.
