### ISSUE TITLE
Many MODS records missing from pending.inverted.mods.xml

### ISSUE THREAD

**Issue by AlisonBabeu** [agile-humanities/perseus-catalog-makeover#25]
Hi @cwulfman . Unless I'm missing something it appears that a good number of MODS records for composite/multi-work volumes did not make it into [pending-inverted.mods.xml](https://github.com/agile-humanities/perseus-catalog-makeover/blob/develop/mods/from_catalog_pending/pending-inverted.mods.xml). 

For example, while I was doing a quick search for several large editions from [Composite Works in catalog_pending](https://github.com/PerseusDL/catalog_pending/tree/master/mods/Composite%20Works) I could not find them in the new inverted MODS record.  For example, there is no MODS record for [Iurisprudentia](https://github.com/PerseusDL/catalog_pending/blob/master/mods/Composite%20Works/Iurisprudentia/iurisprudentia.mods.xml) or for any of the multi-work editions of the [Patrologia Latina](https://github.com/PerseusDL/catalog_pending/tree/master/mods/Composite%20Works/Patrologia%20Latina). Am I looking in the wrong place or did none of these files make it through the conversion?

**Comment by cwulfman** [comment]
That folder wasn't processed because the MODS records in it were different from the rest of those in catalog_pending. I'd forgotten that.

_sigh_.

**Comment by AlisonBabeu** [comment]
Oh dear, I had suspected that when the inverted file seems so sparse. At least I caught it, that's something.

_Double sigh._

**Comment by cwulfman** [comment]
I converted everything in Composite Works; now in a folder Composite_Works in mods/from_catalog_pending.
