### ISSUE TITLE
MODS records missing from pending-singletons.mods.xml

### ISSUE THREAD

**Issue by AlisonBabeu** [agile-humanities/perseus-catalog-makeover#26]
Hi @cwulfman so I've found more missing data as I begin combing through both pending-singletons and pending-inverted.mods.xml.

I had just moved Grammatici Graeci to pending-inverted.mods.xml and moved the two Aelius Herodianus records into the nice structure you created, but unfortunately the two MODS records for Apollonius Dyscolus it appears got lost in the conversion (even though you have them in the Grammatici Graeci structure), in that I can't find them in either pending-singleton or pending-inverted.mods.xml.

The two original records in question are here (https://github.com/PerseusDL/catalog_pending/tree/1d3d0937b0b42add6291a8d5ba5df1b1743de9d3/mods/Apollonius%20Dyscolus). This has also got me to wondering, can we do a sanity check last time like we did in the conversion of catalog_data to make sure there were no records that were lost? I was trying to find the issue where we discussed that but have had no luck so far.

**Comment by cwulfman** [comment]
Yes -- I think we're on the same uneasy page here!

**Comment by AlisonBabeu** [comment]
Just using this is a note of files I know are missing. Took a quick look through the Composite Works folder conversion and it appeared to miss:

CodicesVindobonenses.mods.xml
apocalypsisEsdrasJoannis1866.mods.xml
apocalypsisPetri1908.mods.xml

**Comment by cwulfman** [comment]
Were these records/files ever found?

**Comment by AlisonBabeu** [comment]
Nope, I did not find them in any of the converted records......

**Comment by cwulfman** [comment]
issued moved to PerseusDL/catalog_data issue tracker.
