### ISSUE TITLE
urn:cts:greekLit:tlg0341.tlg002 not represented in AAE spreadsheet

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/perseus-catalog-makeover#27]
there are six versions/editions/translations of tlg0341/tlg002 in catalog_data, but there is no entry with tlg id 0341.002 in AAE.

I had thought all the data could be derived from the AAE spreadsheets. I'm going to go back to catalog_data to harvest all the cts urns and then augment those with data from the spreadsheets to create a comprehensive set of works and expressions.

**Comment by AlisonBabeu** [comment]
I've added it to the spreadsheet, there was a row for it, it must have gotten lost along the way. There is only one other major source of Greek author data missing from the spreadsheets now that I can think of, and that is all of the fragmentary historians with the textgroup of FHG. I had a note to myself to go back and add them to the spreadsheet after I finished adding the list of missing Greek authors late in the spring but have not had a chance as yet...

**Comment by AlisonBabeu** [comment]
Just using this is a note of files I know are missing. Took a quick look through the Composite Works folder conversion and it appeared to miss:

CodicesVindobonenses.mods.xml
apocalypsisEsdrasJoannis1866.mods.xml
apocalypsisPetri1908.mods.xml

**Comment by AlisonBabeu** [comment]
Just realize comment above was on wrong issue. Whoops.
