### ISSUE TITLE
Verify what records were/were not converted to new format

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/perseus-catalog-makeover#28]

**Comment by AlisonBabeu** [comment]
Hi @cwulfman I just took a look at inverted.mods.xml and singletons.mods.xml, the ones in development are not the versions that I sent to you!

**Comment by cwulfman** [comment]
Ok; I'll fix this...

**Comment by AlisonBabeu** [comment]
Thanks!

**Comment by cwulfman** [comment]
Ok -- check now

**Comment by AlisonBabeu** [comment]
Perfect! Thanks!

**Comment by cwulfman** [comment]
The following xquery collects all the ctsurns from the old records and the new records and returns the number of ctsurns that are in the old records but not in the new.  

``` xquery
xquery version "3.0" ;

declare namespace mods = "http://www.loc.gov/mods/v3" ;

let $old_ctsurns := 
    for $id in distinct-values(collection('/db/PerseusCatalogData')//mods:identifier[@type='ctsurn'])
    order by $id
    return <id>{$id}</id>
let $new_ctsurns :=
    for $id in distinct-values(collection('/db/pcat3-data/manifestations')//mods:identifier[@type='ctsurn'])
    order by $id
    return <id>{$id}</id>

let $u := $old_ctsurns except $old_ctsurns
return count($u)
```
When I ran it just now, it returned 0.

**Comment by AlisonBabeu** [comment]
I'm a little confused here, we now that we got all of the data in catalog_data it was left behind dat in catalog_pending that was the issue as I recall, and this type of xquery wouldn't work there as many of the records in catalog_pending don't have CTS URNs?

**Comment by cwulfman** [comment]
Well, that's true enough: I was just thinking about the non-pending data. My bad. I'll keep thinking...
