### ISSUE TITLE
moving MODS files to PerseusDL/catalog_data

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/perseus-catalog-makeover#29]
As we start to wrap things up, we should transfer the new MODS data we've been creating to Perseus. As you may remember, we decided to do all this major reconstruction in a separate repository for several reasons, chief among them being my desire to avoid cluttering the Perseus GitHub repo's history. Now that the big, mass programmatic changes are done, I think it's time to send the new MODS records home!

Last time we talked, you said you wanted four files:

- singletons.mods.xml
- inverted.mods.xml
- pending-singletons.mods.xml
- pending-inverted.mods.xml

Where would you like these to live in PerseusDL/catalog_data?

**Comment by AlisonBabeu** [comment]
They should definitely live in development, but could we hold off on moving them at least until end of the week. I'm doing some changing right now in the Agile repository and hate to slow down! 

Ultimately perhaps the path could be:
//github.com/PerseusDL/catalog_data/tree/development/mods/Converted_MODS
 (or something like that?)

**Comment by cwulfman** [comment]
No hurry! Just starting to plan.

**Comment by cwulfman** [comment]
I've put copies of the four modsCollection files into PerseusDL/catalog_data/catalog_makeover and committed them to the master branch of catalog_data. Those now become the official files and that the official repo for the data -- nothing further should be done in this repository.

**Comment by AlisonBabeu** [comment]
Hi @cwulfman I realized I need a few more files out of there, all the files under the Composite Works directory which were a last minute add in! Thanks!

**Comment by cwulfman** [comment]
Right -- I hadn't realized you hadn't folded them in yet.  I've copied them over to the master branch, in PerseusDL/catalog_data/catalog_makeover/Composite_Works.
