### ISSUE TITLE
Need to ensure no MODS data left behind

### ISSUE THREAD

**Issue by AlisonBabeu** [agile-humanities/perseus-catalog-makeover#5]
Upon first digging in to the invertedSingletonCollection, I noticed the one of the three editions of Apollonius Rhodius was missing. There is no MODS record in this file for urn:cts:greekLit:tlg0001.tlg001.opp-grc1.

I'm opening this issue to track other singleton MODS records that I've found that are missing, and to document any patterns that I find that may have contributed to them not being included.

One thought for the long term, is what is the best way to make sure no data has been left behind?  One method perhaps might be to get a list of CTS URNs from the CITE Collection tables and then check it against the CTS URNs in the two composite MODS files? 
Just first thoughts here.

**Comment by cwulfman** [comment]
In the latest iteration of the singleton collection, there is a MODS for `urn:cts:greekLit:tlg0001.tlg001.opp-grc1`

I wrote a quick-and-dirty XQuery to verify that everything made it over:

```xquery
xquery version "3.1";

declare namespace mods="http://www.loc.gov/mods/v3";


let $old-mods-ids := distinct-values( 
    for $modsid in collection('/db/PerseusCatalogData/mods')//mods:identifier[@type='ctsurn']
    return normalize-space($modsid))
    
let $new-mods-ids := distinct-values( 
    for $modsid in collection('/db/PerseusCatalogData/inverted')//mods:identifier[@type='ctsurn'] 
    return normalize-space($modsid))

for $id in $old-mods-ids
where not($id = $new-mods-ids)
return $id
```

The only ctsurns left out are

1. urn:cts:greekLang:tlg7000.tlg001.perseus-grc4
2. urn:cts:greekLang:tlg7000.tlg001.perseus-grc5

These records are for Perseus editions volumes IV and V of the Greek Anthology; as we're working on hand-crafted replacements for that collection, I'm not concerned.

**Comment by AlisonBabeu** [comment]
Sweet!! And stop working @cwulfman its Friday night.

**Comment by cwulfman** [comment]
:)

On Apr 20, 2018, at 7:09 PM, Alison Babeu <notifications@github.com<mailto:notifications@github.com>> wrote:


Sweet!! And stop working @cwulfman<https://github.com/cwulfman> its Friday night.
