### ISSUE TITLE
The dreaded double <relatedItem type="host"> issue

### ISSUE THREAD

**Issue by AlisonBabeu** [agile-humanities/perseus-catalog-makeover#6]
Placeholder for further content.

**Comment by AlisonBabeu** [comment]
In perusing the invertedCollection.mods.xml file I have discovered that there are a number of multiple monograph records for different series, including Grammaticae Romanae Fragmenta (3 times), Poetae Lyrici Graeci (2 times), Historicorum Romanorum Reliquiae, to name only a few.

The similar issues with the Fragmenta Historicorum Graecorum have been documented in another issue #2

**Comment by cwulfman** [comment]
Merged Grammaticae Romanae Fragmenta; working on others.
