### ISSUE TITLE
multiple records, versions, for Reimer edition of Aristotle's works

### ISSUE THREAD

**Issue by cwulfman** [agile-humanities/perseus-catalog-makeover#7]
Trying to piece together this puzzle and running into unknowns. I've created a temporary modsCollection (Aristotle_opera.modsCollection.xml) and put the various pieces in it; could you help sort these out?

**Comment by AlisonBabeu** [comment]
Thank you for your recent GitHub issue. Unfortunately due to technical issues, the Babeu household will only be reviewing issues opened between the hours of 9 a.m and 4 p.m, EST.  Thank you for your patience! 
😀

**Comment by AlisonBabeu** [comment]
Seriously @cwulfman I'll take a look at this first thing tomorrow and see if I can sort it out.

**Comment by cwulfman** [comment]
Thanks, @AlisonBabeu!
